name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install goyacc
      run: go install golang.org/x/tools/cmd/goyacc@master
    - name: install ragel
      run: sudo apt install ragel
    - name: download go
      run: curl -O https://dl.google.com/go/go1.19.1.linux-amd64.tar.gz
    - name: unpack go
      run: mkdir goinstall && cd goinstall && tar xf ../go1.19.1.linux-amd64.tar.gz
    - name: install vet shadow
      run: PATH=$GOINSTALL/bin:$PATH go install golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow@latest
    - name: install errcheck
      run: PATH=$GOINSTALL/bin:$PATH go install github.com/kisielk/errcheck@latest
    - name: install ineffassign
      run: PATH=$GOINSTALL/bin:$PATH go install github.com/gordonklaus/ineffassign@latest
    - name: install deadcode
      run: PATH=$GOINSTALL/bin:$PATH go install github.com/remyoudompheng/go-misc/deadcode@latest
    - name: build
      run: PATH=$HOME/go/bin:$GOINSTALL/bin:$PATH ./build.sh -t
    - name: run metadb
      run: ./bin/metadb help

